<?php

use Illuminate\Database\Migrations\Migration;

class InsertAllCountries extends Migration
{
    public function up()
    {
        $now = now();

        $countries = collect([
            ['name' => 'Afghanistan', 'isocode_2' => 'AF', 'isocode_3' => 'AFG', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Åland Islands', 'isocode_2' => 'AX', 'isocode_3' => 'ALA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Albania', 'isocode_2' => 'AL', 'isocode_3' => 'ALB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Algeria', 'isocode_2' => 'DZ', 'isocode_3' => 'DZA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'American Samoa', 'isocode_2' => 'AS', 'isocode_3' => 'ASM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Andorra', 'isocode_2' => 'AD', 'isocode_3' => 'AND', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Angola', 'isocode_2' => 'AO', 'isocode_3' => 'AGO', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Anguilla', 'isocode_2' => 'AI', 'isocode_3' => 'AIA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Antarctica', 'isocode_2' => 'AQ', 'isocode_3' => 'ATA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Antigua and Barbuda', 'isocode_2' => 'AG', 'isocode_3' => 'ATG', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Argentina', 'isocode_2' => 'AR', 'isocode_3' => 'ARG', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Armenia', 'isocode_2' => 'AM', 'isocode_3' => 'ARM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Aruba', 'isocode_2' => 'AW', 'isocode_3' => 'ABW', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Australia', 'isocode_2' => 'AU', 'isocode_3' => 'AUS', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Austria', 'isocode_2' => 'AT', 'isocode_3' => 'AUT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Azerbaijan', 'isocode_2' => 'AZ', 'isocode_3' => 'AZE', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bahamas', 'isocode_2' => 'BS', 'isocode_3' => 'BHS', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bahrain', 'isocode_2' => 'BH', 'isocode_3' => 'BHR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bangladesh', 'isocode_2' => 'BD', 'isocode_3' => 'BGD', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Barbados', 'isocode_2' => 'BB', 'isocode_3' => 'BRB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Belarus', 'isocode_2' => 'BY', 'isocode_3' => 'BLR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Belgium', 'isocode_2' => 'BE', 'isocode_3' => 'BEL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Belize', 'isocode_2' => 'BZ', 'isocode_3' => 'BLZ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Benin', 'isocode_2' => 'BJ', 'isocode_3' => 'BEN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bermuda', 'isocode_2' => 'BM', 'isocode_3' => 'BMU', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bhutan', 'isocode_2' => 'BT', 'isocode_3' => 'BTN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bolivia (Plurinational State of)', 'isocode_2' => 'BO', 'isocode_3' => 'BOL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bonaire,Sint Eustatius and Saba', 'isocode_2' => 'BQ', 'isocode_3' => 'BES', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bosnia and Herzegovina', 'isocode_2' => 'BA', 'isocode_3' => 'BIH', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Botswana', 'isocode_2' => 'BW', 'isocode_3' => 'BWA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bouvet Island', 'isocode_2' => 'BV', 'isocode_3' => 'BVT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Brazil', 'isocode_2' => 'BR', 'isocode_3' => 'BRA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'British Indian Ocean Territory', 'isocode_2' => 'IO', 'isocode_3' => 'IOT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'United States Minor Outlying Islands', 'isocode_2' => 'UM', 'isocode_3' => 'UMI', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Virgin Islands (British)', 'isocode_2' => 'VG', 'isocode_3' => 'VGB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Virgin Islands (U.S.)', 'isocode_2' => 'VI', 'isocode_3' => 'VIR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Brunei Darussalam', 'isocode_2' => 'BN', 'isocode_3' => 'BRN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Bulgaria', 'isocode_2' => 'BG', 'isocode_3' => 'BGR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Burkina Faso', 'isocode_2' => 'BF', 'isocode_3' => 'BFA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Burundi', 'isocode_2' => 'BI', 'isocode_3' => 'BDI', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cambodia', 'isocode_2' => 'KH', 'isocode_3' => 'KHM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cameroon', 'isocode_2' => 'CM', 'isocode_3' => 'CMR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Canada', 'isocode_2' => 'CA', 'isocode_3' => 'CAN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cabo Verde', 'isocode_2' => 'CV', 'isocode_3' => 'CPV', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cayman Islands', 'isocode_2' => 'KY', 'isocode_3' => 'CYM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Central African Republic', 'isocode_2' => 'CF', 'isocode_3' => 'CAF', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Chad', 'isocode_2' => 'TD', 'isocode_3' => 'TCD', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Chile', 'isocode_2' => 'CL', 'isocode_3' => 'CHL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'China', 'isocode_2' => 'CN', 'isocode_3' => 'CHN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Christmas Island', 'isocode_2' => 'CX', 'isocode_3' => 'CXR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cocos (Keeling) Islands', 'isocode_2' => 'CC', 'isocode_3' => 'CCK', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Colombia', 'isocode_2' => 'CO', 'isocode_3' => 'COL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Comoros', 'isocode_2' => 'KM', 'isocode_3' => 'COM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Congo', 'isocode_2' => 'CG', 'isocode_3' => 'COG', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Congo (Democratic Republic of the)', 'isocode_2' => 'CD', 'isocode_3' => 'COD', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cook Islands', 'isocode_2' => 'CK', 'isocode_3' => 'COK', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Costa Rica', 'isocode_2' => 'CR', 'isocode_3' => 'CRI', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Croatia', 'isocode_2' => 'HR', 'isocode_3' => 'HRV', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cuba', 'isocode_2' => 'CU', 'isocode_3' => 'CUB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Curaçao', 'isocode_2' => 'CW', 'isocode_3' => 'CUW', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Cyprus', 'isocode_2' => 'CY', 'isocode_3' => 'CYP', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Czech Republic', 'isocode_2' => 'CZ', 'isocode_3' => 'CZE', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Denmark', 'isocode_2' => 'DK', 'isocode_3' => 'DNK', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Djibouti', 'isocode_2' => 'DJ', 'isocode_3' => 'DJI', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dominica', 'isocode_2' => 'DM', 'isocode_3' => 'DMA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dominican Republic', 'isocode_2' => 'DO', 'isocode_3' => 'DOM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ecuador', 'isocode_2' => 'EC', 'isocode_3' => 'ECU', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Egypt', 'isocode_2' => 'EG', 'isocode_3' => 'EGY', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'El Salvador', 'isocode_2' => 'SV', 'isocode_3' => 'SLV', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Equatorial Guinea', 'isocode_2' => 'GQ', 'isocode_3' => 'GNQ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Eritrea', 'isocode_2' => 'ER', 'isocode_3' => 'ERI', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Estonia', 'isocode_2' => 'EE', 'isocode_3' => 'EST', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ethiopia', 'isocode_2' => 'ET', 'isocode_3' => 'ETH', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Falkland Islands (Malvinas)', 'isocode_2' => 'FK', 'isocode_3' => 'FLK', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Faroe Islands', 'isocode_2' => 'FO', 'isocode_3' => 'FRO', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Fiji', 'isocode_2' => 'FJ', 'isocode_3' => 'FJI', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Finland', 'isocode_2' => 'FI', 'isocode_3' => 'FIN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'France', 'isocode_2' => 'FR', 'isocode_3' => 'FRA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'French Guiana', 'isocode_2' => 'GF', 'isocode_3' => 'GUF', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'French Polynesia', 'isocode_2' => 'PF', 'isocode_3' => 'PYF', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'French Southern Territories', 'isocode_2' => 'TF', 'isocode_3' => 'ATF', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Gabon', 'isocode_2' => 'GA', 'isocode_3' => 'GAB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Gambia', 'isocode_2' => 'GM', 'isocode_3' => 'GMB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Georgia', 'isocode_2' => 'GE', 'isocode_3' => 'GEO', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Germany', 'isocode_2' => 'DE', 'isocode_3' => 'DEU', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ghana', 'isocode_2' => 'GH', 'isocode_3' => 'GHA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Gibraltar', 'isocode_2' => 'GI', 'isocode_3' => 'GIB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Greece', 'isocode_2' => 'GR', 'isocode_3' => 'GRC', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Greenland', 'isocode_2' => 'GL', 'isocode_3' => 'GRL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Grenada', 'isocode_2' => 'GD', 'isocode_3' => 'GRD', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guadeloupe', 'isocode_2' => 'GP', 'isocode_3' => 'GLP', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guam', 'isocode_2' => 'GU', 'isocode_3' => 'GUM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guatemala', 'isocode_2' => 'GT', 'isocode_3' => 'GTM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guernsey', 'isocode_2' => 'GG', 'isocode_3' => 'GGY', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guinea', 'isocode_2' => 'GN', 'isocode_3' => 'GIN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guinea-Bissau', 'isocode_2' => 'GW', 'isocode_3' => 'GNB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Guyana', 'isocode_2' => 'GY', 'isocode_3' => 'GUY', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Haiti', 'isocode_2' => 'HT', 'isocode_3' => 'HTI', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Heard Island and McDonald Islands', 'isocode_2' => 'HM', 'isocode_3' => 'HMD', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Holy See', 'isocode_2' => 'VA', 'isocode_3' => 'VAT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Honduras', 'isocode_2' => 'HN', 'isocode_3' => 'HND', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hong Kong', 'isocode_2' => 'HK', 'isocode_3' => 'HKG', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Hungary', 'isocode_2' => 'HU', 'isocode_3' => 'HUN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Iceland', 'isocode_2' => 'IS', 'isocode_3' => 'ISL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'India', 'isocode_2' => 'IN', 'isocode_3' => 'IND', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Indonesia', 'isocode_2' => 'ID', 'isocode_3' => 'IDN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Côte d\'Ivoire', 'isocode_2' => 'CI', 'isocode_3' => 'CIV', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Iran (Islamic Republic of)', 'isocode_2' => 'IR', 'isocode_3' => 'IRN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Iraq', 'isocode_2' => 'IQ', 'isocode_3' => 'IRQ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ireland', 'isocode_2' => 'IE', 'isocode_3' => 'IRL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Isle of Man', 'isocode_2' => 'IM', 'isocode_3' => 'IMN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Israel', 'isocode_2' => 'IL', 'isocode_3' => 'ISR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Italy', 'isocode_2' => 'IT', 'isocode_3' => 'ITA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jamaica', 'isocode_2' => 'JM', 'isocode_3' => 'JAM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Japan', 'isocode_2' => 'JP', 'isocode_3' => 'JPN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jersey', 'isocode_2' => 'JE', 'isocode_3' => 'JEY', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Jordan', 'isocode_2' => 'JO', 'isocode_3' => 'JOR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kazakhstan', 'isocode_2' => 'KZ', 'isocode_3' => 'KAZ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kenya', 'isocode_2' => 'KE', 'isocode_3' => 'KEN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kiribati', 'isocode_2' => 'KI', 'isocode_3' => 'KIR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kuwait', 'isocode_2' => 'KW', 'isocode_3' => 'KWT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Kyrgyzstan', 'isocode_2' => 'KG', 'isocode_3' => 'KGZ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lao People\'s Democratic Republic', 'isocode_2' => 'LA', 'isocode_3' => 'LAO', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Latvia', 'isocode_2' => 'LV', 'isocode_3' => 'LVA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lebanon', 'isocode_2' => 'LB', 'isocode_3' => 'LBN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lesotho', 'isocode_2' => 'LS', 'isocode_3' => 'LSO', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Liberia', 'isocode_2' => 'LR', 'isocode_3' => 'LBR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Libya', 'isocode_2' => 'LY', 'isocode_3' => 'LBY', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Liechtenstein', 'isocode_2' => 'LI', 'isocode_3' => 'LIE', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lithuania', 'isocode_2' => 'LT', 'isocode_3' => 'LTU', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Luxembourg', 'isocode_2' => 'LU', 'isocode_3' => 'LUX', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Macao', 'isocode_2' => 'MO', 'isocode_3' => 'MAC', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Macedonia (the former Yugoslav Republic of)', 'isocode_2' => 'MK', 'isocode_3' => 'MKD', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Madagascar', 'isocode_2' => 'MG', 'isocode_3' => 'MDG', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Malawi', 'isocode_2' => 'MW', 'isocode_3' => 'MWI', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Malaysia', 'isocode_2' => 'MY', 'isocode_3' => 'MYS', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Maldives', 'isocode_2' => 'MV', 'isocode_3' => 'MDV', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mali', 'isocode_2' => 'ML', 'isocode_3' => 'MLI', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Malta', 'isocode_2' => 'MT', 'isocode_3' => 'MLT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marshall Islands', 'isocode_2' => 'MH', 'isocode_3' => 'MHL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Martinique', 'isocode_2' => 'MQ', 'isocode_3' => 'MTQ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mauritania', 'isocode_2' => 'MR', 'isocode_3' => 'MRT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mauritius', 'isocode_2' => 'MU', 'isocode_3' => 'MUS', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mayotte', 'isocode_2' => 'YT', 'isocode_3' => 'MYT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mexico', 'isocode_2' => 'MX', 'isocode_3' => 'MEX', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Micronesia (Federated States of)', 'isocode_2' => 'FM', 'isocode_3' => 'FSM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Moldova (Republic of)', 'isocode_2' => 'MD', 'isocode_3' => 'MDA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Monaco', 'isocode_2' => 'MC', 'isocode_3' => 'MCO', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mongolia', 'isocode_2' => 'MN', 'isocode_3' => 'MNG', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Montenegro', 'isocode_2' => 'ME', 'isocode_3' => 'MNE', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Montserrat', 'isocode_2' => 'MS', 'isocode_3' => 'MSR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Morocco', 'isocode_2' => 'MA', 'isocode_3' => 'MAR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Mozambique', 'isocode_2' => 'MZ', 'isocode_3' => 'MOZ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Myanmar', 'isocode_2' => 'MM', 'isocode_3' => 'MMR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Namibia', 'isocode_2' => 'NA', 'isocode_3' => 'NAM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nauru', 'isocode_2' => 'NR', 'isocode_3' => 'NRU', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nepal', 'isocode_2' => 'NP', 'isocode_3' => 'NPL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Netherlands', 'isocode_2' => 'NL', 'isocode_3' => 'NLD', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'New Caledonia', 'isocode_2' => 'NC', 'isocode_3' => 'NCL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'New Zealand', 'isocode_2' => 'NZ', 'isocode_3' => 'NZL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nicaragua', 'isocode_2' => 'NI', 'isocode_3' => 'NIC', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Niger', 'isocode_2' => 'NE', 'isocode_3' => 'NER', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Nigeria', 'isocode_2' => 'NG', 'isocode_3' => 'NGA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Niue', 'isocode_2' => 'NU', 'isocode_3' => 'NIU', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Norfolk Island', 'isocode_2' => 'NF', 'isocode_3' => 'NFK', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Korea (Democratic People\'s Republic of)', 'isocode_2' => 'KP', 'isocode_3' => 'PRK', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Northern Mariana Islands', 'isocode_2' => 'MP', 'isocode_3' => 'MNP', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Norway', 'isocode_2' => 'NO', 'isocode_3' => 'NOR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Oman', 'isocode_2' => 'OM', 'isocode_3' => 'OMN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Pakistan', 'isocode_2' => 'PK', 'isocode_3' => 'PAK', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Palau', 'isocode_2' => 'PW', 'isocode_3' => 'PLW', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Palestine,State of', 'isocode_2' => 'PS', 'isocode_3' => 'PSE', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Panama', 'isocode_2' => 'PA', 'isocode_3' => 'PAN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Papua New Guinea', 'isocode_2' => 'PG', 'isocode_3' => 'PNG', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Paraguay', 'isocode_2' => 'PY', 'isocode_3' => 'PRY', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Peru', 'isocode_2' => 'PE', 'isocode_3' => 'PER', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Philippines', 'isocode_2' => 'PH', 'isocode_3' => 'PHL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Pitcairn', 'isocode_2' => 'PN', 'isocode_3' => 'PCN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Poland', 'isocode_2' => 'PL', 'isocode_3' => 'POL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Portugal', 'isocode_2' => 'PT', 'isocode_3' => 'PRT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Puerto Rico', 'isocode_2' => 'PR', 'isocode_3' => 'PRI', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Qatar', 'isocode_2' => 'QA', 'isocode_3' => 'QAT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Republic of Kosovo', 'isocode_2' => 'XK', 'isocode_3' => 'KOS', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Réunion', 'isocode_2' => 'RE', 'isocode_3' => 'REU', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Romania', 'isocode_2' => 'RO', 'isocode_3' => 'ROU', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Russian Federation', 'isocode_2' => 'RU', 'isocode_3' => 'RUS', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Rwanda', 'isocode_2' => 'RW', 'isocode_3' => 'RWA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saint Barthélemy', 'isocode_2' => 'BL', 'isocode_3' => 'BLM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saint Helena,Ascension and Tristan da Cunha', 'isocode_2' => 'SH', 'isocode_3' => 'SHN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saint Kitts and Nevis', 'isocode_2' => 'KN', 'isocode_3' => 'KNA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saint Lucia', 'isocode_2' => 'LC', 'isocode_3' => 'LCA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saint Martin (French part)', 'isocode_2' => 'MF', 'isocode_3' => 'MAF', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saint Pierre and Miquelon', 'isocode_2' => 'PM', 'isocode_3' => 'SPM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saint Vincent and the Grenadines', 'isocode_2' => 'VC', 'isocode_3' => 'VCT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Samoa', 'isocode_2' => 'WS', 'isocode_3' => 'WSM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'San Marino', 'isocode_2' => 'SM', 'isocode_3' => 'SMR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sao Tome and Principe', 'isocode_2' => 'ST', 'isocode_3' => 'STP', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Saudi Arabia', 'isocode_2' => 'SA', 'isocode_3' => 'SAU', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Senegal', 'isocode_2' => 'SN', 'isocode_3' => 'SEN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Serbia', 'isocode_2' => 'RS', 'isocode_3' => 'SRB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Seychelles', 'isocode_2' => 'SC', 'isocode_3' => 'SYC', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sierra Leone', 'isocode_2' => 'SL', 'isocode_3' => 'SLE', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Singapore', 'isocode_2' => 'SG', 'isocode_3' => 'SGP', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sint Maarten (Dutch part)', 'isocode_2' => 'SX', 'isocode_3' => 'SXM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Slovakia', 'isocode_2' => 'SK', 'isocode_3' => 'SVK', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Slovenia', 'isocode_2' => 'SI', 'isocode_3' => 'SVN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Solomon Islands', 'isocode_2' => 'SB', 'isocode_3' => 'SLB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Somalia', 'isocode_2' => 'SO', 'isocode_3' => 'SOM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'South Africa', 'isocode_2' => 'ZA', 'isocode_3' => 'ZAF', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'South Georgia and the South Sandwich Islands', 'isocode_2' => 'GS', 'isocode_3' => 'SGS', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Korea (Republic of)', 'isocode_2' => 'KR', 'isocode_3' => 'KOR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'South Sudan', 'isocode_2' => 'SS', 'isocode_3' => 'SSD', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Spain', 'isocode_2' => 'ES', 'isocode_3' => 'ESP', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sri Lanka', 'isocode_2' => 'LK', 'isocode_3' => 'LKA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sudan', 'isocode_2' => 'SD', 'isocode_3' => 'SDN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Suriname', 'isocode_2' => 'SR', 'isocode_3' => 'SUR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Svalbard and Jan Mayen', 'isocode_2' => 'SJ', 'isocode_3' => 'SJM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Swaziland', 'isocode_2' => 'SZ', 'isocode_3' => 'SWZ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Sweden', 'isocode_2' => 'SE', 'isocode_3' => 'SWE', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Switzerland', 'isocode_2' => 'CH', 'isocode_3' => 'CHE', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Syrian Arab Republic', 'isocode_2' => 'SY', 'isocode_3' => 'SYR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Taiwan', 'isocode_2' => 'TW', 'isocode_3' => 'TWN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tajikistan', 'isocode_2' => 'TJ', 'isocode_3' => 'TJK', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tanzania,United Republic of', 'isocode_2' => 'TZ', 'isocode_3' => 'TZA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Thailand', 'isocode_2' => 'TH', 'isocode_3' => 'THA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Timor-Leste', 'isocode_2' => 'TL', 'isocode_3' => 'TLS', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Togo', 'isocode_2' => 'TG', 'isocode_3' => 'TGO', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tokelau', 'isocode_2' => 'TK', 'isocode_3' => 'TKL', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tonga', 'isocode_2' => 'TO', 'isocode_3' => 'TON', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Trinidad and Tobago', 'isocode_2' => 'TT', 'isocode_3' => 'TTO', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tunisia', 'isocode_2' => 'TN', 'isocode_3' => 'TUN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Turkey', 'isocode_2' => 'TR', 'isocode_3' => 'TUR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Turkmenistan', 'isocode_2' => 'TM', 'isocode_3' => 'TKM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Turks and Caicos Islands', 'isocode_2' => 'TC', 'isocode_3' => 'TCA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tuvalu', 'isocode_2' => 'TV', 'isocode_3' => 'TUV', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Uganda', 'isocode_2' => 'UG', 'isocode_3' => 'UGA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ukraine', 'isocode_2' => 'UA', 'isocode_3' => 'UKR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'United Arab Emirates', 'isocode_2' => 'AE', 'isocode_3' => 'ARE', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'United Kingdom of Great Britain and Northern Ireland', 'isocode_2' => 'GB', 'isocode_3' => 'GBR', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'United States of America', 'isocode_2' => 'US', 'isocode_3' => 'USA', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Uruguay', 'isocode_2' => 'UY', 'isocode_3' => 'URY', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Uzbekistan', 'isocode_2' => 'UZ', 'isocode_3' => 'UZB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Vanuatu', 'isocode_2' => 'VU', 'isocode_3' => 'VUT', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Venezuela (Bolivarian Republic of)', 'isocode_2' => 'VE', 'isocode_3' => 'VEN', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Viet Nam', 'isocode_2' => 'VN', 'isocode_3' => 'VNM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Wallis and Futuna', 'isocode_2' => 'WF', 'isocode_3' => 'WLF', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Western Sahara', 'isocode_2' => 'EH', 'isocode_3' => 'ESH', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Yemen', 'isocode_2' => 'YE', 'isocode_3' => 'YEM', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Zambia', 'isocode_2' => 'ZM', 'isocode_3' => 'ZMB', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Zimbabwe', 'isocode_2' => 'ZW', 'isocode_3' => 'ZWE', 'created_at' => $now, 'updated_at' => $now],
        ]);

        if (config('app.env') === 'testing') {
            \DB::table('countries')->insert($countries->slice(0, 10)->all());

            return;
        }

        \DB::table('countries')->insert($countries->all());
    }

    public function down()
    {
        \DB::table('countries')->delete();
    }
}
